server:
  port: 8080

spring:
  application:
    name: logistics-profit-system
  datasource:
    url: jdbc:h2:mem:dashboard
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

dashboard:
  cors:
    enabled: true